WIDTH = 850
HEIGHT = 850

BOARD_WIDTH = WIDTH - 340
BOARD_HEIGHT = HEIGHT - 340

BOARD_ROWS = 4
BOARD_COLS = 4

CELL_WIDTH = BOARD_WIDTH // BOARD_COLS
CELL_HEIGHT = BOARD_HEIGHT // BOARD_ROWS

CELL_COLOR = "#9F4513"
CELL_BORDER = "#D18B47"

BOARD_POS_X = (WIDTH - BOARD_WIDTH) // 2
BOARD_POS_Y = (HEIGHT - BOARD_HEIGHT) // 2

BLACK_PLAYER_COLOR = "#6F2F23"
WHITE_PLAYER_COLOR = "#ffffff"

TINY_GOBBLET = CELL_WIDTH * 0.55
SMALL_GOBBLET = CELL_WIDTH * 0.68
MEDIUM_GOBBLET = CELL_WIDTH * 0.8
LARGE_GOBBLET = CELL_WIDTH * 0.9


BLACK_GOBBLET = "./src/gui/assets/black.png"
WHITE_GOBBLET = "./src/gui/assets/white.png"

PLAYER = {
    "b": ["BLACK", WHITE_PLAYER_COLOR, BLACK_PLAYER_COLOR, BLACK_GOBBLET],
    "w": ["WHITE", BLACK_PLAYER_COLOR, WHITE_PLAYER_COLOR, WHITE_GOBBLET],
}

SIZE = {
    "t": ["TINY", TINY_GOBBLET, 0],
    "s": ["SMALL", SMALL_GOBBLET, 1],
    "m": ["MEDIUM", MEDIUM_GOBBLET, 2],
    "l": ["LARGE", LARGE_GOBBLET, 3],
}

PIECES_SIZES = 4
PIECES_BY_PLAYER = 12

MODES = [["human", "human"], ["human", "ai"], ["ai", "ai"]]
DIFFICULTIES = [["easy", "easy"], ["hard", "easy"], ["easy", "hard"], ["hard", "hard"]]
